<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="css/design.css"/>
</head>
<body>
  <header>Lorem ipsum</header>
  <section class="purplebackground">
  	ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc 
  </section>
  <section class="graybackground">
  	ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec auguxe. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc 
  </section>
  <section class="tanbackground">
  	ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc nkjn.," dictum pharetra. Nulla ac odio. Duis vitae metus ut purus1476 dignissim id, lacus. Curabitur sagittis dolor nec augue. Sed1478 risus eleifend quam, ac semper velit pede convallis arcu.\lips@par}lxdckmasdo;ckadxopc1472 tellus vel odio. Vestibulum ante ipsum primis in faucibus orci1474iho;;s lcx ":ds ncx  km x  m xlmxljmc 
  </section>
  <footer>Lorem ipsum</footer>
</body>
</html>